name: Build font and specimen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Linux dependencies
      run: |
        sudo snap install yq
    - name: Build font
      run: make build
    - name: Check with fontbakery
      run: make test
      continue-on-error: true
    - name: Generate proofs
      run: make proof
    - name: Rearrange
      run: |
          mkdir for-gh-pages
          mv fontbakery-report.html for-gh-pages
          git fetch --depth=1
          mv proof/* for-gh-pages
          git checkout -f gh-pages
          cp -ar for-gh-pages/* .
          rm -rf for-gh-pages
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        file_pattern: fonts *.html
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          fonts
